[package]
name = "dns-mirror"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.9.1"
clap = "2.34"
pktparse = "0.7.0"
log = "0.4"
pretty_env_logger = "0.4.0"

